export const CountryCodes = [
  { countryName: 'Afghanistan', countryCode: '93', countryISO: 'AF' },
  { countryName: 'Albania', countryCode: '355', countryISO: 'AL' },
  { countryName: 'Algeria', countryCode: '213', countryISO: 'DZ' },
  { countryName: 'American Samoa', countryCode: '1-684', countryISO: 'AS' },
  { countryName: 'Andorra', countryCode: '376', countryISO: 'AD' },
  { countryName: 'Angola', countryCode: '244', countryISO: 'AO' },
  { countryName: 'Anguilla', countryCode: '1-264', countryISO: 'AI' },
  { countryName: 'Antarctica', countryCode: '672', countryISO: 'AQ' },
  {
    countryName: 'Antigua and Barbuda',
    countryCode: '1-268',
    countryISO: 'AG',
  },
  { countryName: 'Argentina', countryCode: '54', countryISO: 'AR' },
  { countryName: 'Armenia', countryCode: '374', countryISO: 'AM' },
  { countryName: 'Aruba', countryCode: '297', countryISO: 'AW' },
  { countryName: 'Australia', countryCode: '61', countryISO: 'AU' },
  { countryName: 'Austria', countryCode: '43', countryISO: 'AT' },
  { countryName: 'Azerbaijan', countryCode: '994', countryISO: 'AZ' },
  { countryName: 'Bahamas', countryCode: '1-242', countryISO: 'BS' },
  { countryName: 'Bahrain', countryCode: '973', countryISO: 'BH' },
  { countryName: 'Bangladesh', countryCode: '880', countryISO: 'BD' },
  { countryName: 'Barbados', countryCode: '1-246', countryISO: 'BB' },
  { countryName: 'Belarus', countryCode: '375', countryISO: 'BY' },
  { countryName: 'Belgium', countryCode: '32', countryISO: 'BE' },
  { countryName: 'Belize', countryCode: '501', countryISO: 'BZ' },
  { countryName: 'Benin', countryCode: '229', countryISO: 'BJ' },
  { countryName: 'Bermuda', countryCode: '1-441', countryISO: 'BM' },
  { countryName: 'Bhutan', countryCode: '975', countryISO: 'BT' },
  { countryName: 'Bolivia', countryCode: '591', countryISO: 'BO' },
  {
    countryName: 'Bosnia and Herzegovina',
    countryCode: '387',
    countryISO: 'BA',
  },
  { countryName: 'Botswana', countryCode: '267', countryISO: 'BW' },
  { countryName: 'Brazil', countryCode: '55', countryISO: 'BR' },
  {
    countryName: 'British Indian Ocean Territory',
    countryCode: '246',
    countryISO: 'IO',
  },
  {
    countryName: 'British Virgin Islands',
    countryCode: '1-284',
    countryISO: 'VG',
  },
  { countryName: 'Brunei', countryCode: '673', countryISO: 'BN' },
  { countryName: 'Bulgaria', countryCode: '359', countryISO: 'BG' },
  { countryName: 'Burkina Faso', countryCode: '226', countryISO: 'BF' },
  { countryName: 'Burundi', countryCode: '257', countryISO: 'BI' },
  { countryName: 'Cambodia', countryCode: '855', countryISO: 'KH' },
  { countryName: 'Cameroon', countryCode: '237', countryISO: 'CM' },
  { countryName: 'Canada', countryCode: '1', countryISO: 'CA' },
  { countryName: 'Cape Verde', countryCode: '238', countryISO: 'CV' },
  { countryName: 'Cayman Islands', countryCode: '1-345', countryISO: 'KY' },
  {
    countryName: 'Central African Republic',
    countryCode: '236',
    countryISO: 'CF',
  },
  { countryName: 'Chad', countryCode: '235', countryISO: 'TD' },
  { countryName: 'Chile', countryCode: '56', countryISO: 'CL' },
  { countryName: 'China', countryCode: '86', countryISO: 'CN' },
  { countryName: 'Christmas Island', countryCode: '61', countryISO: 'CX' },
  { countryName: 'Cocos Islands', countryCode: '61', countryISO: 'CC' },
  { countryName: 'Colombia', countryCode: '57', countryISO: 'CO' },
  { countryName: 'Comoros', countryCode: '269', countryISO: 'KM' },
  { countryName: 'Cook Islands', countryCode: '682', countryISO: 'CK' },
  { countryName: 'Costa Rica', countryCode: '506', countryISO: 'CR' },
  { countryName: 'Croatia', countryCode: '385', countryISO: 'HR' },
  { countryName: 'Cuba', countryCode: '53', countryISO: 'CU' },
  { countryName: 'Curacao', countryCode: '599', countryISO: 'CW' },
  { countryName: 'Cyprus', countryCode: '357', countryISO: 'CY' },
  { countryName: 'Czech Republic', countryCode: '420', countryISO: 'CZ' },
  {
    countryName: 'Democratic Republic of the Congo',
    countryCode: '243',
    countryISO: 'CD',
  },
  { countryName: 'Denmark', countryCode: '45', countryISO: 'DK' },
  { countryName: 'Djibouti', countryCode: '253', countryISO: 'DJ' },
  { countryName: 'Dominica', countryCode: '1-767', countryISO: 'DM' },
  {
    countryName: 'Dominican Republic',
    countryCode: '1-809, 1-829, 1-849',
    countryISO: 'DO',
  },
  { countryName: 'East Timor', countryCode: '670', countryISO: 'TL' },
  { countryName: 'Ecuador', countryCode: '593', countryISO: 'EC' },
  { countryName: 'Egypt', countryCode: '20', countryISO: 'EG' },
  { countryName: 'El Salvador', countryCode: '503', countryISO: 'SV' },
  { countryName: 'Equatorial Guinea', countryCode: '240', countryISO: 'GQ' },
  { countryName: 'Eritrea', countryCode: '291', countryISO: 'ER' },
  { countryName: 'Estonia', countryCode: '372', countryISO: 'EE' },
  { countryName: 'Ethiopia', countryCode: '251', countryISO: 'ET' },
  { countryName: 'Falkland Islands', countryCode: '500', countryISO: 'FK' },
  { countryName: 'Faroe Islands', countryCode: '298', countryISO: 'FO' },
  { countryName: 'Fiji', countryCode: '679', countryISO: 'FJ' },
  { countryName: 'Finland', countryCode: '358', countryISO: 'FI' },
  { countryName: 'France', countryCode: '33', countryISO: 'FR' },
  { countryName: 'French Polynesia', countryCode: '689', countryISO: 'PF' },
  { countryName: 'Gabon', countryCode: '241', countryISO: 'GA' },
  { countryName: 'Gambia', countryCode: '220', countryISO: 'GM' },
  { countryName: 'Georgia', countryCode: '995', countryISO: 'GE' },
  { countryName: 'Germany', countryCode: '49', countryISO: 'DE' },
  { countryName: 'Ghana', countryCode: '233', countryISO: 'GH' },
  { countryName: 'Gibraltar', countryCode: '350', countryISO: 'GI' },
  { countryName: 'Greece', countryCode: '30', countryISO: 'GR' },
  { countryName: 'Greenland', countryCode: '299', countryISO: 'GL' },
  { countryName: 'Grenada', countryCode: '1-473', countryISO: 'GD' },
  { countryName: 'Guam', countryCode: '1-671', countryISO: 'GU' },
  { countryName: 'Guatemala', countryCode: '502', countryISO: 'GT' },
  { countryName: 'Guernsey', countryCode: '44-1481', countryISO: 'GG' },
  { countryName: 'Guinea', countryCode: '224', countryISO: 'GN' },
  { countryName: 'Guinea-Bissau', countryCode: '245', countryISO: 'GW' },
  { countryName: 'Guyana', countryCode: '592', countryISO: 'GY' },
  { countryName: 'Haiti', countryCode: '509', countryISO: 'HT' },
  { countryName: 'Honduras', countryCode: '504', countryISO: 'HN' },
  { countryName: 'Hong Kong', countryCode: '852', countryISO: 'HK' },
  { countryName: 'Hungary', countryCode: '36', countryISO: 'HU' },
  { countryName: 'Iceland', countryCode: '354', countryISO: 'IS' },
  { countryName: 'India', countryCode: '91', countryISO: 'IN' },
  { countryName: 'Indonesia', countryCode: '62', countryISO: 'ID' },
  { countryName: 'Iran', countryCode: '98', countryISO: 'IR' },
  { countryName: 'Iraq', countryCode: '964', countryISO: 'IQ' },
  { countryName: 'Ireland', countryCode: '353', countryISO: 'IE' },
  { countryName: 'Isle of Man', countryCode: '44-1624', countryISO: 'IM' },
  { countryName: 'Israel', countryCode: '972', countryISO: 'IL' },
  { countryName: 'Italy', countryCode: '39', countryISO: 'IT' },
  { countryName: 'Ivory Coast', countryCode: '225', countryISO: 'CI' },
  { countryName: 'Jamaica', countryCode: '1-876', countryISO: 'JM' },
  { countryName: 'Japan', countryCode: '81', countryISO: 'JP' },
  { countryName: 'Jersey', countryCode: '44-1534', countryISO: 'JE' },
  { countryName: 'Jordan', countryCode: '962', countryISO: 'JO' },
  { countryName: 'Kazakhstan', countryCode: '7', countryISO: 'KZ' },
  { countryName: 'Kenya', countryCode: '254', countryISO: 'KE' },
  { countryName: 'Kiribati', countryCode: '686', countryISO: 'KI' },
  { countryName: 'Kosovo', countryCode: '383', countryISO: 'XK' },
  { countryName: 'Kuwait', countryCode: '965', countryISO: 'KW' },
  { countryName: 'Kyrgyzstan', countryCode: '996', countryISO: 'KG' },
  { countryName: 'Laos', countryCode: '856', countryISO: 'LA' },
  { countryName: 'Latvia', countryCode: '371', countryISO: 'LV' },
  { countryName: 'Lebanon', countryCode: '961', countryISO: 'LB' },
  { countryName: 'Lesotho', countryCode: '266', countryISO: 'LS' },
  { countryName: 'Liberia', countryCode: '231', countryISO: 'LR' },
  { countryName: 'Libya', countryCode: '218', countryISO: 'LY' },
  { countryName: 'Liechtenstein', countryCode: '423', countryISO: 'LI' },
  { countryName: 'Lithuania', countryCode: '370', countryISO: 'LT' },
  { countryName: 'Luxembourg', countryCode: '352', countryISO: 'LU' },
  { countryName: 'Macao', countryCode: '853', countryISO: 'MO' },
  { countryName: 'Macedonia', countryCode: '389', countryISO: 'MK' },
  { countryName: 'Madagascar', countryCode: '261', countryISO: 'MG' },
  { countryName: 'Malawi', countryCode: '265', countryISO: 'MW' },
  { countryName: 'Malaysia', countryCode: '60', countryISO: 'MY' },
  { countryName: 'Maldives', countryCode: '960', countryISO: 'MV' },
  { countryName: 'Mali', countryCode: '223', countryISO: 'ML' },
  { countryName: 'Malta', countryCode: '356', countryISO: 'MT' },
  { countryName: 'Marshall Islands', countryCode: '692', countryISO: 'MH' },
  { countryName: 'Mauritania', countryCode: '222', countryISO: 'MR' },
  { countryName: 'Mauritius', countryCode: '230', countryISO: 'MU' },
  { countryName: 'Mayotte', countryCode: '262', countryISO: 'YT' },
  { countryName: 'Mexico', countryCode: '52', countryISO: 'MX' },
  { countryName: 'Micronesia', countryCode: '691', countryISO: 'FM' },
  { countryName: 'Moldova', countryCode: '373', countryISO: 'MD' },
  { countryName: 'Monaco', countryCode: '377', countryISO: 'MC' },
  { countryName: 'Mongolia', countryCode: '976', countryISO: 'MN' },
  { countryName: 'Montenegro', countryCode: '382', countryISO: 'ME' },
  { countryName: 'Montserrat', countryCode: '1-664', countryISO: 'MS' },
  { countryName: 'Morocco', countryCode: '212', countryISO: 'MA' },
  { countryName: 'Mozambique', countryCode: '258', countryISO: 'MZ' },
  { countryName: 'Myanmar', countryCode: '95', countryISO: 'MM' },
  { countryName: 'Namibia', countryCode: '264', countryISO: 'NA' },
  { countryName: 'Nauru', countryCode: '674', countryISO: 'NR' },
  { countryName: 'Nepal', countryCode: '977', countryISO: 'NP' },
  { countryName: 'Netherlands', countryCode: '31', countryISO: 'NL' },
  { countryName: 'Netherlands Antilles', countryCode: '599', countryISO: 'AN' },
  { countryName: 'New Caledonia', countryCode: '687', countryISO: 'NC' },
  { countryName: 'New Zealand', countryCode: '64', countryISO: 'NZ' },
  { countryName: 'Nicaragua', countryCode: '505', countryISO: 'NI' },
  { countryName: 'Niger', countryCode: '227', countryISO: 'NE' },
  { countryName: 'Nigeria', countryCode: '234', countryISO: 'NG' },
  { countryName: 'Niue', countryCode: '683', countryISO: 'NU' },
  { countryName: 'North Korea', countryCode: '850', countryISO: 'KP' },
  {
    countryName: 'Northern Mariana Islands',
    countryCode: '1-670',
    countryISO: 'MP',
  },
  { countryName: 'Norway', countryCode: '47', countryISO: 'NO' },
  { countryName: 'Oman', countryCode: '968', countryISO: 'OM' },
  { countryName: 'Pakistan', countryCode: '92', countryISO: 'PK' },
  { countryName: 'Palau', countryCode: '680', countryISO: 'PW' },
  { countryName: 'Palestine', countryCode: '970', countryISO: 'PS' },
  { countryName: 'Panama', countryCode: '507', countryISO: 'PA' },
  { countryName: 'Papua New Guinea', countryCode: '675', countryISO: 'PG' },
  { countryName: 'Paraguay', countryCode: '595', countryISO: 'PY' },
  { countryName: 'Peru', countryCode: '51', countryISO: 'PE' },
  { countryName: 'Philippines', countryCode: '63', countryISO: 'PH' },
  { countryName: 'Pitcairn', countryCode: '64', countryISO: 'PN' },
  { countryName: 'Poland', countryCode: '48', countryISO: 'PL' },
  { countryName: 'Portugal', countryCode: '351', countryISO: 'PT' },
  { countryName: 'Puerto Rico', countryCode: '1-787, 1-939', countryISO: 'PR' },
  { countryName: 'Qatar', countryCode: '974', countryISO: 'QA' },
  {
    countryName: 'Republic of the Congo',
    countryCode: '242',
    countryISO: 'CG',
  },
  { countryName: 'Reunion', countryCode: '262', countryISO: 'RE' },
  { countryName: 'Romania', countryCode: '40', countryISO: 'RO' },
  { countryName: 'Russia', countryCode: '7', countryISO: 'RU' },
  { countryName: 'Rwanda', countryCode: '250', countryISO: 'RW' },
  { countryName: 'Saint Barthelemy', countryCode: '590', countryISO: 'BL' },
  { countryName: 'Saint Helena', countryCode: '290', countryISO: 'SH' },
  {
    countryName: 'Saint Kitts and Nevis',
    countryCode: '1-869',
    countryISO: 'KN',
  },
  { countryName: 'Saint Lucia', countryCode: '1-758', countryISO: 'LC' },
  { countryName: 'Saint Martin', countryCode: '590', countryISO: 'MF' },
  {
    countryName: 'Saint Pierre and Miquelon',
    countryCode: '508',
    countryISO: 'PM',
  },
  {
    countryName: 'Saint Vincent and the Grenadines',
    countryCode: '1-784',
    countryISO: 'VC',
  },
  { countryName: 'Samoa', countryCode: '685', countryISO: 'WS' },
  { countryName: 'San Marino', countryCode: '378', countryISO: 'SM' },
  {
    countryName: 'Sao Tome and Principe',
    countryCode: '239',
    countryISO: 'ST',
  },
  { countryName: 'Saudi Arabia', countryCode: '966', countryISO: 'SA' },
  { countryName: 'Senegal', countryCode: '221', countryISO: 'SN' },
  { countryName: 'Serbia', countryCode: '381', countryISO: 'RS' },
  { countryName: 'Seychelles', countryCode: '248', countryISO: 'SC' },
  { countryName: 'Sierra Leone', countryCode: '232', countryISO: 'SL' },
  { countryName: 'Singapore', countryCode: '65', countryISO: 'SG' },
  { countryName: 'Sint Maarten', countryCode: '1-721', countryISO: 'SX' },
  { countryName: 'Slovakia', countryCode: '421', countryISO: 'SK' },
  { countryName: 'Slovenia', countryCode: '386', countryISO: 'SI' },
  { countryName: 'Solomon Islands', countryCode: '677', countryISO: 'SB' },
  { countryName: 'Somalia', countryCode: '252', countryISO: 'SO' },
  { countryName: 'South Africa', countryCode: '27', countryISO: 'ZA' },
  { countryName: 'South Korea', countryCode: '82', countryISO: 'KR' },
  { countryName: 'South Sudan', countryCode: '211', countryISO: 'SS' },
  { countryName: 'Spain', countryCode: '34', countryISO: 'ES' },
  { countryName: 'Sri Lanka', countryCode: '94', countryISO: 'LK' },
  { countryName: 'Sudan', countryCode: '249', countryISO: 'SD' },
  { countryName: 'Suriname', countryCode: '597', countryISO: 'SR' },
  {
    countryName: 'Svalbard and Jan Mayen',
    countryCode: '47',
    countryISO: 'SJ',
  },
  { countryName: 'Swaziland', countryCode: '268', countryISO: 'SZ' },
  { countryName: 'Sweden', countryCode: '46', countryISO: 'SE' },
  { countryName: 'Switzerland', countryCode: '41', countryISO: 'CH' },
  { countryName: 'Syria', countryCode: '963', countryISO: 'SY' },
  { countryName: 'Taiwan', countryCode: '886', countryISO: 'TW' },
  { countryName: 'Tajikistan', countryCode: '992', countryISO: 'TJ' },
  { countryName: 'Tanzania', countryCode: '255', countryISO: 'TZ' },
  { countryName: 'Thailand', countryCode: '66', countryISO: 'TH' },
  { countryName: 'Togo', countryCode: '228', countryISO: 'TG' },
  { countryName: 'Tokelau', countryCode: '690', countryISO: 'TK' },
  { countryName: 'Tonga', countryCode: '676', countryISO: 'TO' },
  {
    countryName: 'Trinidad and Tobago',
    countryCode: '1-868',
    countryISO: 'TT',
  },
  { countryName: 'Tunisia', countryCode: '216', countryISO: 'TN' },
  { countryName: 'Turkey', countryCode: '90', countryISO: 'TR' },
  { countryName: 'Turkmenistan', countryCode: '993', countryISO: 'TM' },
  {
    countryName: 'Turks and Caicos Islands',
    countryCode: '1-649',
    countryISO: 'TC',
  },
  { countryName: 'Tuvalu', countryCode: '688', countryISO: 'TV' },
  {
    countryName: 'U.S. Virgin Islands',
    countryCode: '1-340',
    countryISO: 'VI',
  },
  { countryName: 'Uganda', countryCode: '256', countryISO: 'UG' },
  { countryName: 'Ukraine', countryCode: '380', countryISO: 'UA' },
  { countryName: 'United Arab Emirates', countryCode: '971', countryISO: 'AE' },
  { countryName: 'United Kingdom', countryCode: '44', countryISO: 'GB' },
  { countryName: 'United States', countryCode: '1', countryISO: 'US' },
  { countryName: 'Uruguay', countryCode: '598', countryISO: 'UY' },
  { countryName: 'Uzbekistan', countryCode: '998', countryISO: 'UZ' },
  { countryName: 'Vanuatu', countryCode: '678', countryISO: 'VU' },
  { countryName: 'Vatican', countryCode: '379', countryISO: 'VA' },
  { countryName: 'Venezuela', countryCode: '58', countryISO: 'VE' },
  { countryName: 'Vietnam', countryCode: '84', countryISO: 'VN' },
  { countryName: 'Wallis and Futuna', countryCode: '681', countryISO: 'WF' },
  { countryName: 'Western Sahara', countryCode: '212', countryISO: 'EH' },
  { countryName: 'Yemen', countryCode: '967', countryISO: 'YE' },
  { countryName: 'Zambia', countryCode: '260', countryISO: 'ZM' },
  { countryName: 'Zimbabwe', countryCode: '263', countryISO: 'ZW' },
];
